unclassified:
    globalLibraries:
        libraries:
            - name: "cr-common"
              defaultVersion: main
              includeInChangesets: false
              retriever:
                modernSCM:
                    scm:
                        git:
                            remote: "https://github.com/jenkins-infra/pipeline-library.git"
                    libraryPath: library/cr-common